# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            geoffreybyers
tagline:          
url:              http://geoffreybyers.github.io
paginate:         3
baseurl:          /
author:
  name:           Geoffrey Byers
  url:            https://twitter.com/geoffreybyers
  email:          geoffreybyers@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
