title:        Geoffrey W. Byers
tagline:      'My Blog'
description:  'My Blog'
url:          http://andhyde.com
version:      1.1.1
author:		  Geoffrey W. Byers
name:         Geoffrey W. Byers
email:        me@geoffreybyers.com
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
