title:        Geoffrey W. Byers
tagline:      'Geoffrey Byers'
description:  'Geoffrey Byers'
url:          http://www.geoffreybyers.github.io
version:      1.1.1
author:		  Geoffrey W. Byers
name:         Geoffrey W. Byers
email:        me@geoffreybyers.com
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
